select * where {
?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?s2.
?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?s1.
?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/MilitaryConflict>.
?s <http://dbpedia.org/property/place> ?p.
?p <http://dbpedia.org/ontology/capital> ?o1.
?p <http://dbpedia.org/property/nativeName> ?o2.
?p <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?o3.
?p <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?o4.
}
