select * where {
?d1 <http://purl.org/dc/terms/subject>  <http://dbpedia.org/resource/Category:Hereditary_cancers>.
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?s2.
?d1 <http://dbpedia.org/ontology/omim> ?o1.
?d1 <http://xmlns.com/foaf/0.1/name> ?o2.
?d1 <http://xmlns.com/foaf/0.1/depiction> ?o3.
?d1 <http://xmlns.com/foaf/0.1/isPrimaryTopicOf> ?o4.
?d1 <http://dbpedia.org/ontology/meshId> ?o5.
?d1 <http://dbpedia.org/property/meshid> ?o6.
?d1 <http://dbpedia.org/ontology/icd10> ?o7.
}
